#!/usr/bin/env node
/**
 * Bundles yt-dlp's "ejs" challenge solver (Unlicense) into src/core/pot/solver.generated.ts.
 * It is the same JavaScript yt-dlp uses to solve YouTube's signature / `n` challenges and is
 * updated by the yt-dlp team whenever YouTube changes its player – re-run this (and rebuild the app)
 * when playback breaks:   npm run fetch-solver
 *
 * Needs python3 + pip (present on GitHub's macOS/Ubuntu runners). Set EJS_VERSION to pin a version.
 */
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const py = process.env.PYTHON ?? 'python3';
const dir = mkdtempSync(join(tmpdir(), 'ejs-'));
const spec = process.env.EJS_VERSION ? `yt-dlp-ejs==${process.env.EJS_VERSION}` : 'yt-dlp-ejs';

function run(cmd, args) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 });
  if (r.status !== 0) {
    console.error(r.stdout, r.stderr);
    throw new Error(`${cmd} ${args.slice(0, 4).join(' ')} failed (exit ${r.status})`);
  }
  return r.stdout;
}

async function fromWheel() {
  run(py, ['-m', 'pip', 'download', spec, '--no-deps', '--only-binary=:all:', '-d', dir]);
  const wheel = readdirSync(dir).find((f) => f.endsWith('.whl'));
  if (!wheel) throw new Error('yt-dlp-ejs wheel not found after pip download');
  const read = (suffix) =>
    run(py, [
      '-c',
      'import sys,zipfile; z=zipfile.ZipFile(sys.argv[1]); n=[x for x in z.namelist() if x.endswith(sys.argv[2])]; ' +
        'sys.stdout.write(z.read(n[0]).decode("utf-8")) if n else sys.exit("not in wheel: "+sys.argv[2])',
      join(dir, wheel),
      suffix,
    ]);
  return { version: wheel.split('-')[1], lib: read('solver/lib.min.js'), core: read('solver/core.min.js') };
}

async function fromRelease() {
  const base = 'https://github.com/yt-dlp/ejs/releases/latest/download/';
  const get = async (name) => {
    const r = await fetch(base + name);
    if (!r.ok) throw new Error(`${name}: HTTP ${r.status}`);
    return r.text();
  };
  return { version: 'github-latest', lib: await get('yt.solver.lib.min.js'), core: await get('yt.solver.core.min.js') };
}

let found;
try {
  found = await fromWheel();
} catch (e) {
  console.warn(`PyPI route failed (${e.message}); trying GitHub release assets…`);
  found = await fromRelease();
}
const { version, lib, core } = found;
if (lib.length < 10_000 || core.length < 1_000) throw new Error('solver files look too small – package layout changed?');

writeFileSync(
  new URL('../src/core/pot/solver.generated.ts', import.meta.url),
  `// GENERATED by scripts/fetch-solver.mjs from yt-dlp-ejs ${version} (Unlicense). Do not edit.\n` +
    `export const SOLVER_LIB = ${JSON.stringify(lib)};\n` +
    `export const SOLVER_CORE = ${JSON.stringify(core)};\n` +
    `export const SOLVER_VERSION = ${JSON.stringify(version)};\n`,
);
console.log(`solver.generated.ts written (yt-dlp-ejs ${version}, lib ${lib.length} B, core ${core.length} B)`);
